### ISSUE TITLE
Review request

### ISSUE THREAD

**Issue by mienaikage** [exercism/raku#430]
Hello @exercism/reviewers,

The Raku repository has a large number of pull requests that require reviews. Almost all of them are JSON changes via the exercise generator, with very little Raku code changes, so I'm hoping they'll all be fairly straightforward!

**Comment by ekingery** [comment]
I'm working through these now. I'll leave the GitHub Actions change for someone else to verify. It looks fine, but I'd like another set of eyes on it as I'm not very familiar with GH Actions. The rest of the code looks good so far, changes are all consistent. @mienaikage , thanks for taking this on! I coded perl professionally many years ago, glad to see this track get some attention!

**Comment by ekingery** [comment]
Calling @iHiD, I'm on the reviewers team, but it appears my approvals are not sufficient for merging (see #407). Could you advise or fix me up with the correct permissions?

**Comment by iHiD** [comment]
Should be now! :)

**Comment by ekingery** [comment]
> Should be now! :)

Looks good, thanks!

**Comment by ekingery** [comment]
I think we should be all set here, let me know if I missed any. I'll check in on #406 early next week.

**Comment by iHiD** [comment]
Thanks @ekingery!
